<?php
return [

  'bills' => [
        'DEBT' => 'Долг',
        'DEBT_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'PAID' => 'Оплачен',
        'PAID_colors' => ['color' => '#388E3C', 'background' => '#E8F5E9'],
        'CANCELLED' => 'Отменен',
        'CANCELLED_colors' => ['color' => '#546E7A', 'background' => '#ECEFF1'],
        'DECLINED' => 'Отклонен',
        'DECLINED_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
        'HOLD' => 'Холд',
        'HOLD_colors' => ['color' => '#1565C0', 'background' => '#E3F2FD'],
        'NEW' => 'Новый',
        'NEW_colors' => ['color' => '#009688', 'background' => '#E0F2F1'],
        'ERR: CONFIRM' => 'Ошибка: Подтверждение',
        'ERR: CONFIRM_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
        'ERR: DECLINE' => 'Ошибка: Отмена',
        'ERR: DECLINE_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
        'ERR: HOLD' => 'Ошибка: Холд',
        'ERR: HOLD_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],

        'CARTREK' => 'CarTrek',
        'RENT' => 'Аренда',
        'ABONEMENT' => 'Абонемент',
        'FREE' => 'Бесплатно',
        'FINE' => 'Штраф',
        'TURBO' => 'Турбо-проверка',
        'BONUS' => 'Покупка бонусов',
        'BONUS PAY' => 'BONUS PAY',
        'INSURANCE' => 'Страховка',
        'ERROR' => 'Ошибка',
        'D_RENT' => 'D_RENT',
        'DONATION' => 'Пожертвование',
        'ARENDA' => 'Прайм',
        'REGISTRATION' => 'Регистрация',
        '' => 'NULL',
    ],

    'orders' => [
        'FINISHED' => 'Завершен',
        'DRIVE_PREPAID' => 'Поездка абонемент',
        'PARK_PREPAID' => 'Парковка абонемент',
        'DRIVE' => 'Поездка',
        'PARK' => 'Парковка',
        'BOOK' => 'Бронь',
        'BOOK_PAID' => 'Бронь платная',
        'INSPECT' => 'Осмотр',
        'INSPECT_PAID' => 'Осмотр платный',

        'PAID' => 'Оплачен',
        'PAID_colors' => ['color' => '#388E3C', 'background' => '#E8F5E9'],
        'PARTIAL_PAID' => 'Частично оплачен',
        'PARTIAL_PAID_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'CANCELLED' => 'Отменен',
        'CANCELLED_colors' => ['color' => '#546E7A', 'background' => '#ECEFF1'],
        'ERROR' => 'Ошибка',
        'ERROR_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
    ],

    'fines' => [
        'PAID' => 'Оплачен',
        'PAID_colors' => ['color' => '#388E3C', 'background' => '#E8F5E9'],
        'NEW' => 'Не оплачен',
        'NEW_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
    ],

    'transactions' => [
        'SUCCESS' => 'Успешно',
        'SUCCESS_colors' => ['color' => '#388E3C', 'background' => '#E8F5E9'],
        'CANCELLED' => 'Отменен',
        'CANCELLED_colors' => ['color' => '#546E7A', 'background' => '#ECEFF1'],
        'DECLINED' => 'Отклонен',
        'DECLINED_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'HOLD' => 'Холд',
        'HOLD_colors' => ['color' => '#1565C0', 'background' => '#E3F2FD'],
        'NEW' => 'Новый',
        'NEW_colors' => ['color' => '#009688', 'background' => '#E0F2F1'],
        'MINIMUM' => 'Минимум',
        'MINIMUM_colors' => ['color' => '#009688', 'background' => '#E0F2F1'],
        'ERR: CONFIRM' => 'Ошибка: Подтверждение',
        'ERR: CONFIRM_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
        'ERR: DECLINE' => 'Ошибка: Отмена',
        'ERR: DECLINE_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
        'ERR: HOLD' => 'Ошибка: Холд',
        'ERR: HOLD_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
    ],

    'instant_registrations' => [
        'ACTIVATED' => 'Активирован',
        'ACTIVATED_colors' => ['color' => '#388E3C', 'background' => '#E8F5E9'],
        'DENY' => 'Отклонен',
        'DENY_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'NEW' => 'Новый',
        'NEW_colors' => ['color' => '#009688', 'background' => '#E0F2F1'],
        'CANCELLED' => 'Отмена клиентом',
        'CANCELLED_colors' => ['color' => '#546E7A', 'background' => '#ECEFF1'],
    ],

    'bonus_requests' => [
        'DECLINED' => 'Оплата не прошла',
        'DECLINED_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'SUCCESS' => 'Успешно',
        'SUCCESS_colors' => ['color' => '#388E3C', 'background' => '#E8F5E9'],
        'NEW' => 'Новый',
        'NEW_colors' => ['color' => '#009688', 'background' => '#E0F2F1'],
    ],

    'alerts' => [
        'BURGLARY' => 'Вскрытие',
        'BURGLARY_DOORS' => 'Вскрытие двери',
        'BURGLARY_HOOD' => 'Вскрытие капота',
        'BURGLARY_TRUNK' => 'Вскрытие багажника',
        'BURGLARY_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'BURGLARY_DOORS_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'BURGLARY_HOOD_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'BURGLARY_TRUNK_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'THEFT' => 'Угон',
        'THEFT_colors' => ['color' => '#E53935', 'background' => '#FFEBEE'],
        'EVACUATION' => 'Эвакуация',
        'EVACUATION_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
        'SPEEDING' => 'Скорость 120 км/ч',
        'SPEEDING_colors' => ['color' => '#546E7A', 'background' => '#ECEFF1'],
        'SPEEDING_FINE' => 'Штраф 130 км/ч',
        'SPEEDING_FINE_colors' => ['color' => '#546E7A', 'background' => '#ECEFF1'],
        'OFFLINE' => 'Нет связи',
        'OFFLINE_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
        'LEAVING_USING_AREA' => 'Выезд из зоны',
        'LEAVING_USING_AREA_colors' => ['color' => '#546E7A', 'background' => '#ECEFF1'],
        'DISCHARGED' => 'Разряжен АКБ',
        'DISCHARGED_colors' => ['color' => '#FFA000', 'background' => '#FFF8E1'],
        'DRIFT' => 'Дрифт',
        'DRIFT_colors' => ['color' => '#546E7A', 'background' => '#ECEFF1'],
    ],


 ];
