<div class="row center-xs center-sm center-md center-lg ">
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-9">
    <div class="box">
      <div class="row center-xs center-sm center-md left-lg top-lg top-xs top-sm top-md">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="box">
            <div class="row center-xs start-sm start-md start-lg" >
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 top-10 bottom-10">
                <div class="box sec" ><h1><img src="/yllo.png"><sup><font id="half-black"><small> β</font></small></sup></h2></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 top-10">
          <div class="box">
            <div class="row end-xs end-sm end-md end-lg" >
              <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 half-black if-hover round-button sec" ><a href="#test-popup" class="open-popup-link">
                <div class="box top-20 bottom-20" id="white" align="center">Cоздать цель</div></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row center-xs center-sm center-md center-lg top-20 bottom-40" >
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-6 " >
    <div class="box white round">
      <div class="row center-xs center-sm center-md center-lg top-50 " >
        <div class="col-xs-11 col-sm-11 col-md-10 col-lg-10 round" >
          <div class="box"><input type="text" placeholder="Название" class="light-gray shadow-inset3"></div>
        </div>
      </div>
      <div class="row center-xs center-sm center-md center-lg" >
        <div class="col-xs-11 col-sm-11 col-md-10 col-lg-10" >
          <div class="box">
            <div class="row center-xs center-sm center-md start-lg" >
              <div class="col-xs-11 col-sm-11 col-md-10 col-lg-12 top-10" >
                <div class="box" id="dark-gray" align="right">0/50</div>
              </div>
            </div>
          </div>
        </div>
      </div>


      <div class="row center-xs center-sm center-md center-lg top-20" >
        <div class="col-xs-11 col-sm-11 col-md-10 col-lg-10 round border9" >
          <div class="box">
            <div class="row center-xs center-sm center-md center-lg b-bottom" >
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/dinosaur_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/binoculars_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/pens-pencils_64-new.png" ></div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/ball_64-new.png" ></div>
              </div>
            </div>
            <div class="row center-xs center-sm center-md center-lg b-bottom" >
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/ball_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/pens-pencils_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/pin_64-new.png" ></div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/dinosaur_64-new.png" ></div>
              </div>
            </div>
            <div class="row center-xs center-sm center-md center-lg b-bottom" >
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/dinosaur_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/binoculars_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/ball_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 round  light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/pens-pencils_64-new.png" ></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--
      <div class="row center-xs center-sm center-md center-lg" >
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-12 light-gray-hover round-bottom" >
          <div class="box top-20 bottom-20" id="coub2"><i class="fa fa-refresh"></i> Показать больше</div>
        </div>
      </div>-->

      <div class="row center-xs center-sm center-md center-lg top-40 bottom-50" >
        <div class="col-xs-10 col-sm-10 col-md-8 col-lg-8 border border-hover round-button if-hover sec" id="if">
          <div class="box top-20 bottom-20 " id="white-hover">Создать</h4></div>
        </div>
      </div>

    </div>
  </div>
</div>
