<div class="row center-xs center-sm center-md center-lg ">
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-9">
    <div class="box">
      <div class="row center-xs center-sm center-md left-lg top-lg top-xs top-sm top-md">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="box">
            <div class="row center-xs start-sm start-md start-lg" >
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 top-10 bottom-10">
                <div class="box sec" ><h1><img src="/yllo.png"><sup><font id="half-black"><small> β</font></small></sup></h2></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 top-10">
          <div class="box">
            <div class="row end-xs end-sm end-md end-lg" >
              <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 half-black if-hover round-button sec" ><a href="#test-popup2" class="open-popup-link">
                <div class="box top-20 bottom-20" id="white" align="center">Cоздать цель</div></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--
<div class="row center-xs center-sm center-md center-lg top-20 bottom-20" >
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-9" >
    <div class="box">
      <div class="row center-xs center-sm center-md center-lg" >
        <div class="col-xs-11 col-sm-10 col-md-9 col-lg-8" >
          <div class="box" id="white"><img src="/img/full.png" width="50%"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row center-xs center-sm center-md center-lg top-40 bottom-20" >
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-9" >
    <div class="box">
      <div class="row center-xs center-sm center-md center-lg" >
        <div class="col-xs-11 col-sm-10 col-md-9 col-lg-8" >
          <div class="box" id="white"><img src="/yllo3.png"></div>
        </div>
      </div>
    </div>
  </div>
</div>-->

<div class="row center-xs center-sm center-md center-lg top-20">
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-9">
    <div class="box">
      <div class="row center-xs center-sm center-md center-lg">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6" >
          <div class="box top-20 bottom-20 sec round cursor" id="if-hover"><h4><i class="fa fa-random"></i> Перемешать</b></h4></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row center-xs center-sm center-md center-lg top-10" >
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-9" >
    <div class="box ">
      <div class="row center-xs center-sm center-md center-lg" >
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 top-10 bottom-10" >
          <div class="box top-30 bottom-30 white round ">
            <div class="row center-xs center-sm center-md center-lg" >
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 bottom-10" align="center" >
                <div class="box img-128" style="background-image: url(/alien_128-new.png);"></div>
              </div>
              <div class="col-xs-10 col-sm-10 col-md-9 col-lg-9 bottom-30" >
                <div class="box" id="coub2"><h4><a href="/flex" class="test2">Вместе поехать на выходные в снежком</a></h4></div>
              </div>
              <div class="col-xs-8 col-sm-7 col-md-6 col-lg-6 light-gray shadow-inset2 round-button">
                <div class="box ">
                  <div class="row if round-button space-6" style="width:100%"></div>
                </div>
              </div>

            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 top-10 bottom-10" >
          <div class="box top-30 bottom-30 round white sec">
            <div class="row center-xs center-sm center-md center-lg" >
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 top-10 bottom-20" >
                <div class="box" align="center"><div class="img-64" style="background-image: url(http://zxstella.people.si.umich.edu/prototype/assets/root/c2c2a1dc572ec013a675a69f673ba9d1.png);"></div></div>
                <div class="box top-10" id="if" align="center"><a href="" class="test">Seva Onosov</a></div>
              </div>
              <div class="col-xs-10 col-sm-10 col-md-9 col-lg-9 bottom-30" >
                <div class="box" id="coub2"><h4><a href="/flex" class="test2">Вместе поехать на выходные в снежком</a></h4></div>
              </div>
              <div class="col-xs-10 col-sm-10 col-md-9 col-lg-7 if-hover round-button border sec" id="if">
                <div class="box top-10 bottom-10" id="white-hover">Участвовать</div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 top-10 bottom-10" >
          <div class="box top-30 bottom-30 white round">
            <div class="row center-xs center-sm center-md center-lg" >
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 top-10 bottom-10" align="center">
                <div class="box" align="center"><div class="img-64" style="background-image: url(http://zxstella.people.si.umich.edu/prototype/assets/root/c2c2a1dc572ec013a675a69f673ba9d1.png);"></div></div>
              </div>
              <div class="col-xs-10 col-sm-10 col-md-9 col-lg-9 top-10 bottom-30" >
                <div class="box" id="coub2"><h4><a href="/flex" class="test2">Вместе поехать на выходные в снежком</a></h4></div>
              </div>
              <div class="col-xs-8 col-sm-7 col-md-6 col-lg-6 light-gray shadow-inset2 round-button">
                <div class="box ">
                  <div class="row if round-button space-6" style="width:60%"></div>
                </div>
              </div>
              <div class="col-xs-10 col-sm-10 col-md-9 col-lg-9 top-20" >
                <div class="box" id="dark-gray"><i class="fa fa-check"></i> 3 совпадения</div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 top-10 bottom-10" >
          <div class="box top-30 bottom-30 white round light-gray-hover sec">
            <div class="row center-xs center-sm center-md center-lg" >
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 bottom-10" >
                <div class="box" align="center"><div class="img-128" style="background-image: url(/dinosaur_128-new.png);"></div></div>
              </div>
              <div class="col-xs-10 col-sm-10 col-md-9 col-lg-9 bottom-30" >
                <div class="box" id="coub2"><h4>Вместе поехать на выходные в снежком</h4></div>
              </div>
              <div class="col-xs-8 col-sm-7 col-md-6 col-lg-6 light-gray shadow-inset2 round-button">
                <div class="box ">
                  <div class="row if round-button space-6" style="width:100%"></div>
                </div>
              </div>
              <div class="col-xs-10 col-sm-10 col-md-9 col-lg-9 top-10" >
                <div class="box" id="dark-gray">8 мест</div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 top-10 bottom-10" >
          <div class="box top-30 bottom-30 white round light-gray-hover sec">
            <div class="row center-xs center-sm center-md center-lg" >
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 bottom-10" >
                <div class="box" align="center"><div class="img-128" style="background-image: url(/ball_128-new.png););"></div></div>
              </div>
              <div class="col-xs-10 col-sm-10 col-md-9 col-lg-9 bottom-30" >
                <div class="box" id="coub2"><h4>Вместе поехать на выходные в снежком</h4></div>
              </div>
              <div class="col-xs-8 col-sm-7 col-md-6 col-lg-6 light-gray shadow-inset2 round-button">
                <div class="box ">
                  <div class="row if round-button space-6" style="width:100%"></div>
                </div>
              </div>
              <div class="col-xs-10 col-sm-10 col-md-9 col-lg-9 top-10" >
                <div class="box" id="dark-gray">8 мест</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row center-xs center-sm center-md center-lg top-20 bottom-10">
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-9">
    <div class="box top-20 bottom-20  border-new border-hover sec round-button" id="if-hover">Архив действий</b></div>
  </div>
</div>

<div class="row center-xs center-sm center-md center-lg">
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-9 top-10 bottom-10 ">
    <div class="box">
      <div class="row center-xs center-sm center-md start-lg middle-lg middle-md" >
        <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2" >
          <div class="box top-20 bottom-10" id="white">© 2015</div>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-2 col-lg-7" >
          <div class="box top-20 bottom-10" id="white">О проекте</div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3" >
          <div class="box">
            <div class="row center-xs center-sm center-md center-lg top-10" >
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 " >
                <div class="box top-20 bottom-20 half-black round pink-hover sec"><i class="fa fa-sign-out"></i> Выйти</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="row center-xs center-sm center-md center-lg ">
  <div class="col-xs-11 col-sm-11 col-md-10 col-lg-6 white-popup mfp-hide" id="test-popup" >
    <div class="box">

      <div class="row center-xs center-sm center-md center-lg top-50 " >
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 round light-gray" >
          <div class="box"><input type="text" placeholder="Название" class="light-gray"></div>
        </div>
      </div>
      <div class="row center-xs center-sm center-md end-lg" >
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 top-10" >
          <div class="box" id="half-white" align="right">0/50</div>
        </div>
      </div><!--
      <div class="row center-xs center-sm center-md center-lg top-20" >
        <div class="col-xs-11 col-sm-11 col-md-10 col-lg-10 round border9" >
          <div class="box">
            <div class="row center-xs center-sm center-md center-lg b-bottom" >
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 b-right light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/dinosaur_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 b-right light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/binoculars_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 b-right light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/pens-pencils_64-new.png" ></div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/ball_64-new.png" ></div>
              </div>
            </div>
            <div class="row center-xs center-sm center-md center-lg b-bottom" >
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 b-right light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/ball_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 b-right light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/pens-pencils_64-new.png" ></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 b-right light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/pin_64-new.png" ></div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 light-gray-hover" >
                <div class="box top-20 bottom-20" id="deep-purple"><img src="/dinosaur_64-new.png" ></div>
              </div>
            </div>
          </div>
        </div>
      </div>-->
      <div class="row center-xs center-sm center-md center-lg top-40 bottom-50" id="if">
        <div class="col-xs-10 col-sm-10 col-md-6 col-lg-6  if-hover round-button sec border round-button" id="white-hover">
          <div class="box  top-20 bottom-20 " id="white-hover">Создать</h4></div>
        </div>
      </div>

    </div>
  </div>
</div>


    </div>
  </div>
</div>

<div class="row center-xs center-sm center-md center-lg ">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 white-popup mfp-hide" id="test-popup2" >
    <div class="box">


      <div class="row center-xs center-sm center-md center-lg top-20 bottom-10">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 white round" s.tyle="background-image: url(https://scontent-frt3-1.xx.fbcdn.net/hphotos-xfp1/t39.3138-6/s526x296/12057250_1650070318583939_1679844677_n.png);background-repeat:no-repeat;background-size:100%">
          <div class="box">
            <div class="row center-xs center-sm center-md center-lg ">
              <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11 top-30 " >
                <div class="box" align="left" id="light-green"><i class="fa fa-check-circle"></i> Выполнен</div>
              </div>
              <!--<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" >
                <div class="box" align="center"><div class="img-128" style="background-image: url(/dinosaur_128-new.png);"></div></div>
              </div>-->
              <div class="col-xs-11 col-sm-10 col-md-9 col-lg-8 top-40 bottom-20" >
                <div class="box" id="coub2"><h2><b>Вместе поехать на выходные в снежком</b></h2></div>
              </div>
            </div>
            <div class="row center-xs center-sm center-md center-lg middle-lg middle-md middle-sm">
              <div class="col-xs-11 col-sm-6 col-md-6 col-lg-6 top-30 bottom-10" >
                <div class="box">
                  <div class="row center-xs center-sm center-md center-lg">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 border-right">
                      <div class="box" align="center"><div class="img-64" style="background-image: url(http://zxstella.people.si.umich.edu/prototype/assets/root/c2c2a1dc572ec013a675a69f673ba9d1.png);"></div></div>
                      <div class="box top-20" id="if" align="center"><a href="" class="test">Seva Onosov</a></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 top-30 bottom-10" >
                <div class="box">
                  <div class="row center-xs center-sm center-md center-lg">
                    <div class="col-xs-8 col-sm-10 col-md-8 col-lg-6 border round-button sec top-10 bottom-10">
                      <div class="box " id="if">Участвовать</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row center-xs center-sm center-md center-lg round-bottom bottom-10 " id="gray">
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 top-30 bottom-30 round" >
                <div class="box"><i class="fa fa-vk fa-3x"></i></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 top-30 bottom-30 round" >
                <div class="box"><i class="fa fa-facebook-official fa-3x"></i></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 top-30 bottom-30 round " >
                <div class="box"><i class="fa fa-twitter fa-3x"></i></div>
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 top-30 bottom-30 round" >
                <div class="box"><i class="fa fa-share-alt fa-3x"></i></div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>


<script>
$(document).ready(function() {
  $('.open-popup-link').magnificPopup({
    type:'inline',
    midClick: true // Allow opening popup on middle mouse click. Always set it to true if you don't provide alternative source in href.
  });
});
</script>
