
<div class="row center-xs center-sm center-md center-lg middle-xs middle-sm middle-md middle-lg" style="height:100%">
  <div class="col-xs-11 col-sm-10 col-md-8 col-lg-7">
    <div class="box">
      <div class="row center-xs center-sm center-md center-lg">
        <div class="col-xs col-sm col-md col-lg">
          <div class="box top-20 bottom-40"><img src="/logo-avansik.png"></div>
        </div>
      </div>
      <div class="row center-xs center-sm center-md center-lg half-black round shadow-inset" id="white">
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 half-black-new-hover round-left">
          <div class="box top-20 bottom-20"><i class="fa fa-instagram fa-4x"></i></div>
        </div>
        <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 start-xs start-sm start-md start-lg half-black-new-hover round-right ">
          <div class="box top-30 bottom-30"><h1>Введите текст</h1></div>
        </div>
      </div>
      <div class="row center-xs center-sm center-md center-lg">
        <div class="col-xs-12 col-sm-11 col-md-10 col-lg-9">
          <div class="box">
            <div class="row center-xs center-sm center-md center-lg" >
              <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                <div class="box top-20 bottom-20">Цвет</div>
              </div>

              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-lg-offset-2">
                <div class="box top-20 bottom-20">Размер</div>
              </div>
            </div>
            <div class="row center-xs center-sm center-md center-lg middle-lg " >
              <div class="col-xs col-sm col-md col-lg ">
                <div class="box white round">
                  <div class="row center-xs center-sm center-md center-lg" >
                    <div class="col-xs col-sm col-md col-lg ">
                      <div class="box top-20 bottom-20 round half-black-new-hover shadow" id="coub2">Белый</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xs col-sm col-md col-lg ">
                <div class="box half-black round">
                  <div class="row center-xs center-sm center-md center-lg" >
                    <div class="col-xs col-sm col-md col-lg ">
                      <div class="box top-20 bottom-20 round half-black-new-hover shadow-inset" id="white">Черный</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xs col-sm col-md col-lg "></div>
              <div class="col-xs col-sm col-md col-lg ">
                <div class="box white round" id="coub2">
                  <div class="row center-xs center-sm center-md center-lg" >
                    <div class="col-xs col-sm col-md col-lg ">
                      <div class="box top-20 bottom-20 round half-black-new-hover shadow">S</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xs col-sm col-md col-lg ">
                <div class="box half-black round">
                  <div class="row center-xs center-sm center-md center-lg" >
                    <div class="col-xs col-sm col-md col-lg ">
                      <div class="box top-20 bottom-20 round half-black-new-hover shadow-inset">M</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xs col-sm col-md col-lg ">
                <div class="box half-black round">
                  <div class="row center-xs center-sm center-md center-lg" >
                    <div class="col-xs col-sm col-md col-lg ">
                      <div class="box top-20 bottom-20 round half-black-new-hover shadow-inset">L</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row center-xs center-sm center-md center-lg" >
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                <div class="box top-20 bottom-20">Количество</div>
              </div>
            </div>
            <div class="row center-xs center-sm center-md center-lg middle-lg" >
              <div class="col-xs col-sm col-md col-lg round border-new">
                <div class="box ">
                  <div class="row center-xs center-sm center-md center-lg" >
                    <div class="col-xs col-sm col-md col-lg round-left half-black-new-hover">
                      <div class="box top-20 bottom-20 ">‒</h4></div>
                    </div>
                    <div class="col-xs col-sm col-md col-lg half-black shadow-inset">
                      <div class="box top-20 bottom-20 ">1</h4></div>
                    </div>
                    <div class="col-xs col-sm col-md col-lg round-right half-black-new-hover">
                      <div class="box top-20 bottom-20">+</h4></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row center-xs center-sm center-md center-lg middle-xs middle-sm middle-md middle-lg top-20 bottom-20" >
              <div class="col-xs col-sm col-md col-lg">
                <div class="box top-20 bottom-20"> <h3>250 руб.</h3></div>
              </div>
              <div class="col-xs col-sm col-md col-lg if round-button">
                <div class="box top-20 bottom-20" id="white">Купить</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
